### ISSUE TITLE
Don't use the pipeworks "connection" overlay image on the front

### ISSUE THREAD

**Issue by VanessaE** [Sokomine/locks#2]
https://github.com/Sokomine/locks/blob/master/shared_locked_furnace.lua#L36

This doesn't work with animated images due to an engine/client rendering bug. Instead, you just get a highly distorted, scaled copy of the "animated" image and "connection" instead of seeing the flames animate behind the "connection" overlay.  Besides, the overlay isn't supposed to be used on the front anyway. :-)

**Comment by Sokomine** [comment]
Somehow that change got lost. The new version now shows the locks symbol as overlay and the pipeworks texture only on all other sides (if pipeworks is installed).
